[package]
name = "async_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async = { version = "1.7.0", default-features = false, features = ["std"]}